# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs: 
  - job: job1
    steps:
    - script: echo build job1
  - job: job2
    steps:
    - script: echo build job2

- stage: Test
  dependsOn: Build
  jobs:
  - job: job1
    steps:
    - script: echo Test 

- stage: QA_deploy 
  dependsOn: Build
  jobs:
    - job: job1
      steps:
      - script: echo QA-deploy

- stage: Prod_deploy
  dependsOn: 
  - Test
  - QA_deploy
  jobs:
  - job: job1
    steps:
    - script: echo Prod-deploy

