# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


strategy:
  matrix:
    linux:
      operatingSystem: 'ubuntu-latest'
    windows:
      operatingSystem: 'windowsos-latest'
pool:
  vmImage: $(operatingSystem)

jobs:
- job: Job1
 
  steps:
  - script: echo job-1 Hello, world changed!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

- job: Job2
  dependsOn: Job1
  steps:
  - script: echo job-2
    displayName: 'Run a one-line script'

- job: Job3
  dependsOn: Job2
  steps:
  - script: |
       echo job-3
       echo another multiline
    displayName: 'Run a script'


